### ISSUE TITLE
Rename bio to avoid folder name collision with Biopython's Bio

### ISSUE THREAD

**Issue by peterjc** [ylathouris/bio#1]
Your use of ``bio/`` (lower case) is unfortunately causing a conflict on Windows machines with the long established use of ``Bio/`` (title case) by Biopython, see:

https://github.com/biopython/biopython/issues/2363
https://github.com/pypa/pip/issues/3309

Would you consider renaming your new project to avoid this? Thank you!

**Comment by chris-rands** [comment]
+1 it does seem also from the [dependency graph ](https://github.com/ylathouris/bio/network/dependents) that there is some confusion between `biopython` and `bio` unfortunately. I hope a solution can be found that works for everyone

**Comment by ylathouris** [comment]
Hi,

Apologies for the late response. I have removed bio from pypi now. The name is available. (See https://github.com/biopython/biopython/issues/2363#issuecomment-667360050)
